config/routes.rb
WikipagesWeb::Application.routes.draw do
  resources :contacts, :except => :show

  root :to => 'contacts#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  attr_accessible :name, :phone, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])

    if @contact.save
      flash[:notice] = "Your contact was successfully created."
      redirect_to contacts_path
    else
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update_attributes(params[:contact])
      flash[:notice] = "Your contact was successsfully updated."
      redirect_to contacts_path
    else
      render :edit
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    flash[:notice] = "Your contact was successfully deleted."
    redirect_to contacts_path
  end

  def index
    @contacts = Contact.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<% if @contact.errors.any? %>
  <div class="alert alert-error">
    <h3>Please correct these problems:</h3>
    <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit :class => 'btn btn-primary' %>
<% end %>

app/views/contacts/edit.html.erb
<% provide :title, "Edit #{@contact.name}" %>

<h1><%= yield :title %></h1>

<% if @contact.errors.any? %>
  <h3>Please correct these problems:</h3>
  <ul>
    <% @contact.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit %>
<% end %>

app/views/contacts/index.html.erb
<h1> Wiki-contacts</h1>

<table class="table">
  <tr>
    <td>Name</td>
    <td>Phone</td>
    <td>Email</td>
    <td></td>
    <td></td>
  </tr>
  <% @contacts.each do |contact| %>
    <tr>
      <td><%= contact.name %></td>
      <td><%= contact.phone %></td>
      <td><%= contact.email %></td>
      <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
      <td><%= link_to 'Delete', contact, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Add contact', new_contact_path, :class => 'btn btn-primary' %></p>

app/views/contacts/new.html.erb
<%= flash[:notice] %>
<%= flash[:alert] %>

<h1>New contact</h1>

<% if @contact.errors.any? %>
  <h3>Please correct these problems:</h3>
  <ul>
    <% @contact.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WikipagesWeb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>

  <ul class="nav nav-pills">
    <li class="active"><a href="#">Regular link</a></li>
    <li class="dropdown" id="menu1">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
        Dropdown
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><a href="#">Action</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li class="divider"></li>
        <li><a href="#">Separated link</a></li>
      </ul>
    </li>
    <li class="dropdown" id="menu2">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#menu2">
        Something
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><a href="#">Action</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li class="divider"></li>
        <li><a href="#">Separated link</a></li>
      </ul>
    </li>
  </ul>

  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-error"><%= flash[:alert] %></div>
    <% end %>

    <%= yield %>
  </div>
</body></html>